name: tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and start containers
        run: |
          docker compose up -d --build
          docker ps -a

      - name: Wait for postgres
        run: |
          sleep 20

      - name: Run tests
        run: |
          docker compose exec -T pg ./run_tests.sh
